default: &default
  adapter: postgresql
  pool: 5
  port: 5432
  username: <%= ENV['SHOP_DATABASE_USERNAME'] %>
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: JRShop_development

test:
  <<: *default
  database: JRShop_test

production:
  <<: *default
  database: JRShop_production
